name: solray
description: SolRay mobile client — connects to any SolRay instance by URL.
publish_to: "none"
version: 1.6.2+2

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  shared_preferences: ^2.3.2
  web_socket_channel: ^3.0.1
  file_picker: ^8.1.2
  flutter_local_notifications: ^17.2.3
  app_settings: ^5.1.1
  open_filex: ^4.5.0
  path_provider: ^2.1.4
  share_plus: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
